apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clean-elasticsearch.fullname" . }}-config
  labels:
    {{- include "clean-elasticsearch.labels" . | nindent 4 }}
data:
  ES_IP: "{{ .Values.elasticsearch.ip }}"
  ES_PORT: "{{ .Values.elasticsearch.port }}"
  DATELIMIT: "{{ .Values.datelimit }}"
